---
- hosts: ihab
  become: true
  vars_files: 
    - vars/main.yml 
    - vars/main-credentials.yml
  tasks:
    - name: copy file for {{user}}
      # copy:
      #   src: "data/file.txt"
      #   dest: "/file.txt"
      template:
        src: "data/file.txt.j2"
        dest: "/file.txt"