---
- hosts: ihab
  become: true
  
  tasks:
    - name: test shell
      shell: cat test.txt
      register: result
    
    - name: debug output ansible
      debug:
        var: result.stdout_lines