---
- hosts: ihab
  become: true
  tasks:
    - name: install apache2
      apt:
        name:
          - apache2
        update_cache: yes
      
    - name: copy file
      copy:
        src: html/
        dest: /var/www/html/
     
  
  handlers:
    - name: start apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
    #   command: systemctl start apache2 
