---
# tasks file for tools
  - name: install all packages for docker debian
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - git
    when: ansible_facts['os_family'] == 'Debian'

  - name: add gpg key debian
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    when: ansible_facts['os_family'] == 'Debian'

  - name: add linux repository for docker debian
    apt_repository:
      repo: deb https://download.docker.com/linux/debian stretch stable
    when: ansible_facts['os_family'] == 'Debian'

  - name: install docker component debian
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
    notify: start docker
    when: ansible_facts['os_family'] == 'Debian'

  - name: add redhat repository for docker redhat
    yum_repository:
      name: dockerrepo
      baseurl: https://download.docker.com/linux/rhel/docker-ce.repo
      description: repo for docker
    when: ansible_facts['os_family'] == 'RedHat'

  - name: install docker component redhat
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
    notify: start {{service_name}}
    when: ansible_facts['os_family'] == 'RedHat'
  - name: install docker-compose
    shell: curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

